### ISSUE TITLE
I get an error using it

### ISSUE THREAD

**Issue by reiniertc** [Tieske/fibaroHue#1]
Hi, 
If I use your lua script in Hc2, I get an error:
attempt to index global 'Net' (a nil value)

any idea what goes wrong? (i'm new at lua)

thanks!
Reinier

**Comment by Tieske** [comment]
Looked into it, but it seems they changed the Lua api. The network function for performing an http request (to access the Philips Hue bridge) have changed apparently. Unfortunately I don't have a system available to test it against.

By the way; what firmware version do you have? I think I wrote this on a 3.x version

**Comment by reiniertc** [comment]
Thanks for looking into it.
I tried to implemented in a lua scene, but that doesnt work.
When I copy the code to a virtual device, it works like a charm!

Met vriendelijke groet,

Reinier E. Taudin Chabot

**Comment by Tieske** [comment]
Glad it's fixed!
